options:
    openstack-origin:
        default: distro
        type: string
        description: |
          Repository from which to install.  May be one of the following:
          distro (default), ppa:somecustom/ppa, a deb url sources entry,
          or a supported Cloud Archive release pocket.

          Supported Cloud Archive sources include: cloud:precise-folsom,
          cloud:precise-folsom/updates, cloud:precise-folsom/staging,
          cloud:precise-folsom/proposed.

          When deploying to Precise, the default distro option will use
          the cloud:precise-folsom/updates repository instead, since Cinder
          was not available in the Ubuntu archive for Precise and is only
          available via the Ubuntu Cloud Archive.
    enabled-services:
        default: all
        type: string
        description: |
            If splitting cinder services between units, define which services
            to install and configure.
    block-device:
        default: sdb
        type: string
        description: |
            The *available* block device on which to create LVM volume group.
            May also be set to None for deployments that will not need local
            storage (eg, Ceph/RBD-backed volumes).
    volume-group:
        default: cinder-volumes
        type: string
        description: Name of volume group to create and store Cinder volumes.
    overwrite:
        default: "false"
        type: string
        description: |
            If true, charm will attempt to overwrite block devices containin
            previous filesystems or LVM, assuming it is not in use.
    db-user:
        default: cinder
        type: string
        description: Username to request database access.
    cinder-db:
        default: cinder
        type: string
        description: Database to request access.
    rabbit-user:
        default: cinder
        type: string
        description: Username to request access on rabbitmq-server.
    rabbit-vhost:
        default: cinder
        type: string
        description: RabbitMQ virtual host to request access on rabbitmq-server.
    api-listening-port:
        default: 8776
        type: int
        description: OpenStack Volume API listening port.
    region:
        default: RegionOne
        type: string
        description: OpenStack Region
    # HA configuration settings
    vip:
        type: string
        description: "Virtual IP to use to front cinder API in ha configuration"
    vip_iface:
        type: string
        default: eth0
        description: "Network Interface where to place the Virtual IP"
    vip_cidr:
        type: int
        default: 24
        description: "Netmask that will be used for the Virtual IP"
    ha-bindiface:
        type: string
        default: eth0
        description: |
          Default network interface on which HA cluster will bind to communication
          with the other members of the HA Cluster.
    ha-mcastport:
        type: int
        default: 5401
        description: |
          Default multicast port number that will be used to communicate between
          HA Cluster nodes.
    # Per-service HTTPS configuration.
    ssl_cert:
        type: string
        description: |
          SSL certificate to install and use for API ports.  Setting this value
          and ssl_key will enable reverse proxying, point Glance's entry in the
          Keystone catalog to use https, and override any certficiate and key
          issued by Keystone (if it is configured to do so).
    ssl_key:
        type: string
        description: SSL key to use with certificate specified as ssl_cert.
